services:
  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: key_cloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_FEATURES=token-exchange
      - KC_FEATURES=admin-fine-grained-authz
    command:
      - start-dev --features=token-exchange,admin-fine-grained-authz
    ports:
      - 9001:8080
  appoint-gateway:
    container_name: appoint-gateway
    image: mrsisk/appoint-gateway:latest
    environment:
      - ACCOUNTS_URL=http://host.docker.internal:8084
      - API_URL=http://host.docker.internal:8082
    ports:
      - 8888:8083
    networks:
      - spring

networks:
  spring:
    driver: bridge
