server:
  port: 8083

accounts:
  url: ${ACCOUNTS_URL}
api:
  url: ${API_URL}

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200,http://localhost:8083"
            allowedHeaders: "*"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE